= *Halving Proposals*
:toc:
:toclevels: 3
:sectnums:

[.text-center]
Final Draft +
November 20, 2023 +
Commissioned by the Stacks Foundation +
Jesse Soslowfootnote:[While Jesse is a lawyer, nothing in this paper should be construed as legal advice. The proposals discussed in this report are potential recommendations and have not been analyzed for legal risks.]

[.text-center]
[%hardbreaks]
7th Avenue Group
jesse@7avenue.co
www.7avenue.co

[.text-center]
*About 7th Avenue Group*

7th Avenue Group is a boutique consulting firm that helps businesses solve a wide array of problems. We have over 30 years’ experience founding, building and operating technology companies, including in the web, mobile, SaaS, consumer, and crypto spaces, in both B2B and B2C models.

We’ve built products used by more than half of the Fortune 100, and we’ve founded or operated companies that have raised over $300 million from top investors, including Sequoia Capital, Union Square Ventures and Andreessen Horowitz.

[.mark]#If there’s a new market you need to get into, an initial product idea that you want to explore, or an important strategic decision you need to analyze, we can plug into your team and help you get it done.#

[%always]
<<<

== Background*
=== *Overview*
[.normal]
This report examines various potential adjustments to the Stacks mining emissions schedule, and their potential implications. In a prior, companion report, available here [[.mark]#NEED LINK#] (the “*Emissions Report*”), we analyzed the potential risks to the Stacks blockchain of the upcoming halving of its mining block reward as planned in or around January 2025. That report ultimately recommended the Stacks community consider an adjustment to the timing of the first halving, and this report proposes and analyzes specific alternative mining schedules the Stacks community might adopt.

At the time of the currently-planned Stacks halving, the mining reward for Stacks miners will drop from 1000 Stacks per block to 500 Stacks per block, if no changes to the Stacks blockchain code are made.

In that Emissions Report we identified a few significant risks to the Stacks blockchain of the coinbase halving moving forward as anticipated. The main risks we identified are (1) continued and even further centralization of Stacks mining, and (2) creating barriers to the potential success of sBTC.

With respect to the first issue, we noted in the Emissions Report that: +
____
_Miner centralization is already a problem on the Stacks network. For 95% of the blocks mined on the Stacks network [as of the date of analysis of the Emissions Report], there have only been between 4 and 9 miners. The halving will exacerbate this problem, potentially decreasing the number of miners by half or more. Moreover, as of late, new applications on Bitcoin itself have shown the potential for increasing Bitcoin fees. If Bitcoin fees were to continue to increase, we would expect that even fewer miners, independent of the coinbase value, would be able to profitability mine on the Stacks blockchain, leading again to even greater miner centralization._
____


And, with respect to the second issue, we noted that: +
____
_sBTC functionality will be heavily intertwined with the Stacking functionality. Most importantly for our purposes, the amount of Bitcoin that can be held as part of the sBTC protocol will be directly related to the amount of Stacks held in Stacking. For Stackers to want to lock up and hold their Stacks in the Stacking protocol, the rate of Stacking rewards must be attractive enough for them. Unfortunately, we would expect that the halving will cause a significant decrease in the rate of Stacking rewards, potentially leading to a significant decrease in Stacking participation. If that were to occur, the viability of sBTC as a system that could support large-scale projects could be in jeopardy._
____

Ultimately, the Emissions Report recommends that the Stacks community consider some adjustment to the current emissions schedule, to allow for a longer period during which miners are awarded the current coinbase award of 1000 Stacks per block.

This analysis is a follow up to the Emissions Report, in which we analyze some potential adjustments to the emissions schedule. We take for granted that the Stacks community has an appetite to make an adjustment to the emissions schedule, but of course this may be controversial. Agreement around this threshold issue must first be reached.

The goal of this report, along with the Emissions Report, is to provide some analysis to aid the Stacks community as it debates and considers how it might approach these potential issues.

=== *Original Emissions Schedule*

The original emissions schedule, at the launch of the Stacks blockchain, dictated that, for the first approximately 4 years of the blockchain, the coinbase would be 1000 Stacks tokens per block.footnote:[For the first 10,000 blocks of the Stacks blockchain there was an additional mining bonus of approximately 1,446 Stacks per block, meaning the coinbase for those first 10,000 blocks was approximately 2,446 Stacks per block.] Then that would be cut in half to 500 Stacks tokens per block for the following 4 years. Then that would be cut in half to 250 Stacks tokens per block for the following 4 years. And, finally, that would be cut in half to 125 Stacks tokens per block for all years following.

Our understanding was that it was in fact the original intention that each halving would take place with the Bitcoin halving. And so, as an example, we might have expected that during the next Bitcoin halving that is currently anticipated to take place in April 2024, the initial Stacks halving would also take place.

However, it appears that this alignment was not implemented and, instead, the initial halving of the Stacks blockchain is currently anticipated to take place around January 2025, with the following halvings anticipated to take place approximately four years thereafter, and so on.

Original projections for Stacks emissions, prior to the launch of Stacks, estimated that the total circulating supply for Stacks tokens would be 1.818 billion in the year 2050.footnote:[There is nothing particularly important about the year 2050, but that year had been used widely as a baseline for understanding future emissions of the Stacks blockchain as well as others.]

As part of this analysis, we created an updated model of Stacks emissions based on data from over two years of the Stacks blockchain running, in order to understand whether the original projections remain accurate. The model is available here for anyone to copy and insert their own inputs for analysis: [[.mark]#NEED LINK#].

We found that based on the rate of creation of Stacks blocks and more accurate timing for halvings, the 2050 supply appears to be closer to around 1.787 billion Stacks tokens rather than 1.818 billion. Which means that, if all else is to remain the same, we’d estimate that the 2050 supply would be about 31 million fewer tokens than had originally been projected.

== *Potential Emissions Adjustments*
=== *Summary*

Given the potential negative impact of the upcoming halving, we believe it would be appropriate for the Stacks community to consider adjustments to the Stacks emissions schedule. In the sections below, we first lay out a framework for evaluating potential adjustments to the emissions schedule, and then propose in detail a handful of adjusted emissions schedules that the Stacks community might consider implementing.

We do not believe there exists a single optimal answer to what the emissions schedule should be, but rather there are various possibilities depending on what the Stacks community most values. We do not claim to know what that is, nor seek to impose upon the Stacks community a particular answer. Instead, we’ve identified a few criteria that the Stacks community may wish to optimize for, and what some resulting schedules may look like, assuming optimization for those criteria.

As discussed more fully below, the Stacks community may wish to optimize for keeping the 1000 Stacks block reward in place for as long as feasible, and/or it may wish to maintain the 2050 supply at the originally-projected 1.818 billion Stacks, and/or it may wish to maintain a gradual decrease to its halving schedule with a 50% reduction every 4 years. However, these criteria cannot all exist at the same time; choosing two means the exclusion of the third.

In the sections below, we propose various schedules that optimize for each subset of two of the three criteria and then analyze those schedules.

If forced to choose, we ultimately believe that a schedule that allows for a modest increase in the 2050 supply (increasing the total 2050 supply by ~2.8%), but allowing for the current 1000 Stacks block reward to run through 2028 with then quadrennial “true” halvings, where the supply decreases by 50% at each halving, may be the most promising option. Such a schedule allows for a reasonable balance between all factors and provides the Stacks ecosystem ample time to mature into a smaller block reward.

We provide more details and analysis on this potential approach, as well as other options in the sections below.

=== *Framework for Evaluating Adjustments*

If the Stacks community determines that it wants to make a change to the emissions schedule, it first needs to decide what it is optimizing for. We’ve identified a few different criteria through which it may evaluate a change to the network.

As primary examples, the Stacks community could evaluate any change to the emissions schedule through the following, optimizing for one or multiple at the expense of others:

. Maintain the current block reward at 1000 Stacks for as long as feasible, essentially optimizing for maximum ecosystem maturity prior to an initial halving.
. Maintain the 2050 supply at the originally-projected 1.818 billion Stacks, ensuring that there is no further dilution to Stacks holders when viewed through the lens of 2050 supply.
. Maintain a halving schedule whereby each halving decreases the supply by 50% every ~4 years, ensuring a relatively gradual decrease in block rewards going forward.

As it turns out, these three priorities present something of a trilemma. If, for instance, one were to prioritize 1 and 2, by having the block reward remain at 1000 Stacks for another cycle through about April 2028 and maintain the 2050 supply at 1.818 billion Stacks, then you’d need to have a rapid decrease of block rewards for future “halvings” that would decrease the number of Stacks by more than 50% for each halving.

If, instead, you wanted to optimize for 1 and 3, by having the block reward remain at 1000 Stacks for another cycle through about April 2028 and have a gradual decrease of block rewards every 4 years by 50%, then the 2050 supply would be a bit in excess of the originally projected 1.818 billion Stacks.

And, lastly, if you wanted to optimize for 2 and 3, by maintaining the 2050 supply of 1.818 billion Stacks and have a gradual decrease of block rewards every 4 years by 50%, then the amount of time for which you could continue a 1000 Stacks block reward would be limited.

=== *Potential Emissions Schedules*

We’ll now present and discuss some example emissions schedules that optimize for certain of the criteria discussed above, and some potential advantages and disadvantages of such schedules.

==== *Schedule Optimized for Criteria 1 and 2*

We’ll start with an example emission schedule that is optimized for extending the length of time for which we have 1000 Stacks block reward for as long as feasible (criterion 1), while also maintaining the 2050 supply to the originally-projected 1.818 billion Stacks tokens (criterion 2).

Although one could certainly disagree with what one considers “feasible,” we think that extending the 1000 Stacks block reward for one additional four-year Bitcoin halving cycle until (approximately) mid-2028, is likely the tail-end of what would be considered acceptable by the Stacks community, and therefore feasible.

For one reason, we estimate that the Stacks blockchain would reach a total circulating supply of around 1.818 billion in December of 2030 if the Stacks block reward remained at 1000 Stacks per block through that time. This would leave an emissions budget of 0 Stacks for 2030 through 2050 if the aim was to maintain a 2050 circulating supply of 1.818 billion Stacks.

Therefore there isn’t much time beyond mid-2028 for which the Stacks blockchain could maintain a 1000 Stacks per block budget while retaining a reasonable emissions budget for the remaining years between that time and 2050.

If we therefore assume that the longest feasible time period for maintaining a 1000 Stacks per block reward is through the mid-2028 Bitcoin halving while maintaining the 2050 circulating supply of 1.818 billion, and lock in those variables, we can quickly see the implications.

An actual halving (i.e., decrease by half) of the Stacks block reward every Bitcoin halving cycle would not work. If the Stacks block reward would decrease by 50% at each Bitcoin halving cycle starting in mid-2028 and continuing through 2050 (i.e., 500 Stacks starting mid-2028, 250 Stacks starting mid-2032, 125 Stacks starting mid-2036, etc.) then the total circulating supply at 2050 would be approximately 1.870 billion as opposed to the originally-projected 1.818 billion. While this is only a 2.8% increase, it does not meet the second criterion, which is what we’re optimizing for here.

Short of introducing a burning mechanism into the Stacks blockchain (which would be out of scope for this analysis), there would be only two options (or a combination thereof) to keep the 2050 supply at 1.818 billion Stacks and have the block reward remain 1000 through mid-2028:

. The halving cycles could remain every 4 years, and at the same time as the Bitcoin halvings, but the block reward would need to decrease by more than 50% at least once.
. The block rewards could decrease by 50% at each halving, but the halvings would have to be more frequent (at least in the earlier years) than every 4 years and would therefore (at least for certain halvings) not align with Bitcoin halvings.

We can look at examples of both of these approaches.

An example of the first approach, where the halving cycles remain in line with Bitcoin halvings, but the block reward decreases by more than 50% for certain halvings, could look like the following:

The Stacks block reward remains at 1000 through the next Bitcoin halving around mid-2028, at which time it drops to 400 Stacks per block (a 60% drop). The following Bitcoin halving in mid-2032, the Stacks block reward drops to 150 Stacks per block (a 62.5% drop). Following that the Stacks block reward would truly halve (i.e., drop by 50%) at each Bitcoin halving thereafter. Here’s a chart:

[width="100%",cols="34%,33%,33%",options="header",]
|===
|*Halving Number* |*Approximate Timing* |*Stacks Block Reward After Halving*
|1st |Mid-2028 |400
|2nd |Mid-2032 |150
|3rd |Mid-2036 |75
|4th |Mid-2040 |37.5
|5th |Mid-2044 |18.75
|6th |Mid-2048 |9.375
|===

With the above halving schedule, we estimate the 2050 total circulating supply to be 1.818 billion. We’ll refer to this schedule as “Schedule A.”

We can also construct a halving schedule that follows the second approach. For this halving schedule, each halving will be true halvings (in that the block reward will drop by 50%), but they will need to be more frequent than every four years. Such a halving schedule could look like the following:

The Stacks block reward would remain at 1000 Stacks per block through mid-2028. It would then drop to 500 Stacks per block and remain at 500 Stacks per block through mid-2030 (only 2 years instead of 4 years). Two years later, at mid-2032 aligned with the Bitcoin halving, the reward would drop to 125 Stacks per block. Thereafter the halvings would align with Bitcoin halvings, dropping to 62.5 Stacks per block in mid-2036 and then dropping to 31.25 Stacks per block in mid-2040. Here’s a chart:

[width="100%",cols="34%,33%,33%",options="header",]
|===
|*Halving Number* |*Approximate Timing* |*Stacks Block Reward After Halving*
|1st |Mid-2028 |500
|2nd |Mid-2030 |250
|3rd |Mid-2032 |125
|4th |Mid-2036 |62.5
|5th |Mid-2040 |31.25
|===

This halving schedule would result in a 2050 total circulating supply of around 1.810 billion Stacks – in fact about 8 million Stacks fewer than the originally-projected 1.818 billion Stacks. We’ll refer to this schedule as “Schedule B.”

==== *Schedule Optimized for Criteria 2 and 3*
We’ll next look at a proposed schedule that seeks to maintain the 2050 supply (2), but also maintains a gradual 50% halving every four years (3).

One way to do this is to push back the halving that would result in a 250 block reward from mid-2028 to mid-2032, and have every four year halvings from then forward. One could then move the halving from 1000 Stacks per block to 500 Stacks per block from April 2024 to an off-cycle halving around December 2025 or January 2026. The schedule would look like this:

[width="100%",cols="34%,33%,33%",options="header",]
|===
|*Halving Number* |*Approximate Timing* |*Stacks Block Reward After Halving*
|1st |Late 2025 / Early 2026 |500
|2nd |Mid-2032 |250
|3rd |Mid-2036 |125
|4th |Mid-2040 |62.5
|5th |Mid-2044 |31.25
|6^th^ |Mid-2048 |15.625
|===

This schedule would result in a 2050 total circulating supply of approximately 1.818 billion Stacks. It would also maintain a fairly gradual decrease in block rewards over time, however it wouldn’t increase additional time with a 1000 Stack block reward too significantly.

There would only be about a year or a year and a half, depending, of additional time with a 1000 Stack block reward. We’ll refer to this schedule as “Schedule C.”

==== *Schedule Optimized for Criteria 1 and 3*

Lastly, we’ll look at a schedule that’s optimized for extending the period of 1000 Stacks for as long as feasible (1), combined with a gradual halving of block rewards over the standard four-year period (3).

This schedule, in a sense, creates itself based on the constraints. If we return to our assumption from 2.3.1 that the longest feasible time for a 1000 Stacks block reward would be mid-2028, and then implement a four-year halving schedule from there, we end up with something like the following:

[width="100%",cols="34%,33%,33%",options="header",]
|===
|*Halving Number* |*Approximate Timing* |*Stacks Block Reward After Halving*
|1st |Mid-2028 |500
|2nd |Mid-2032 |250
|3rd |Mid-2036 |125
|4th |Mid-2040 |62.5
|5th |Mid-2044 |31.25
|6th |Mid-2048 |15.625
|===

With the above emissions schedule, the 2050 fully circulating supply is estimated to be around 1.870 billion Stacks tokens. This is an approximate 2.8% increase from the originally-projected 1.818 billion. We’ll refer to this schedule as “Schedule D.”

=== *Analysis*

We reiterate again that ultimately the right changes to the Stacks emissions schedule need to be grounded in the priorities of the Stacks community. We do not believe there is necessarily a “correct” answer.

That said, we do believe that there is greater risk allowing the current halving schedule to continue as originally implemented, as opposed to making some adjustments that could allow for increased runway, and Stacks ecosystem maturation, at the current 1000 Stacks per block emissions rate.

In addition to the various issues raised in the Emissions Report, it might be helpful as a quick point of reference to consider the amount of Stacks’ supply that will be emitted in block rewards in comparison to a more mature blockchain such as Bitcoin. As an example, if nothing were to change, Stacks would add 1.58% of its supply in emissions in 2025 (approximately 4 years after the launch of Stacks). It would gradually decrease from there. On the other hand, Bitcoin’s emissions in 2023, which is approximately 14 years after the creation of Bitcoin, will add approximately 1.72% to Bitcoin’s supply.

We should recognize that Stacks and Bitcoin emissions are very different, and therefore comparing these numbers is not something on which we should rely heavily. For one thing, there was a sale of Stacks tokens prior to launch, whereas Bitcoin emissions came entirely from mining. Naturally this will result in a smaller percentage of the supply coming from mining for Stacks than for Bitcoin.

Nevertheless, the discrepancy is stark. Only four years into Stacks existence, it will be emitting a smaller portion of its supply than Bitcoin does at 14 years in. This minimal emissions budget so early on may not be ideal for Stacks, particularly in light of the specific risks and issues we discuss in the Emissions Report.

Given all of this, we believe it would be reasonable for the Stacks community to prioritize the first criterion – that is, seeking to extend the period for which 1000 Stacks are emitted for as long as reasonable.

The alternative would be to prioritize only the second and third criteria, which would leave you with something like emissions Schedule C. This results in extending the halving by about a year, which isn’t a very long time. It’s conceivable that the same issues that Stacks faces today, as described in the Emissions Report, would still be there. Of course, it remains possible the issues Stacks faces today will still be there in four years, but at least there would be a significant time period allowing for Stacks to mature out of these issues.

If we then assume that we’re optimizing for the first criterion, the question then becomes whether we also optimize for the second criterion or for the third criterion, as it can’t be both. We believe this question ultimately boils down to the following:

____
Is it preferable for the Stacks community to have some increased chance of needing to adjust the emissions schedule again later, or accept now some (relatively small) increase in inflation to decrease the risk of needing future adjustments?
____

We’ll seek to identify some pros and cons of both options.

For the first, we think some pros of maintaining the 2050 total supply, is that it may simply not be necessary to have any greater emissions in the 2028-2050 time period than would be set out in Schedules A and B. Stacks may appreciate in value, or there may be other changes to the network, such that the block rewards set out in those schedules are sufficient to reach the goals of the Stacks community during that time period. In other words, this option maintains optionality with respect to increasing the supply. In addition, this option does not increase network dilution on the 2050 time-scale, which may be quite appealing to token holders.

We think the primary con of keeping the 2050 supply constant is that it increases the risk of issues related to a fairly rapid decrease in block rewards. Of course, as discussed immediately above, the Stacks community would potentially have the flexibility to adjust the block reward, but that would require both foresight into those issues, and community consensus to proactively make an adjustment. This paper assumes there is community consensus for an adjustment today (or it just won’t happen), but there may not be in four years. It may be risky to assume that, if issues appear imminent, changes will necessarily be accepted by the broader Stacks community.

We see the primary pro of a gradual, four-year halving schedule that does not necessarily keep the 2050 supply unchanged, as simply the inverse of the con mentioned immediately above. That is, it is creating the conditions for the Stacks ecosystem to minimize its risk with respect to the value of its block reward. Like Bitcoin’s system, it could give a four-year time period to each block reward epoch, following which there would be a 50% decrease. This system seems to have worked well for Bitcoin to-date, and we believe generally wise for Stacks to follow and emulate the model.

The primary con of this approach is that there will be some increased inflation. The increased inflation will level out over time, starting higher in the earlier years and then decreasing. Ultimately, with Schedule D, the circulating supply would be expected to be less than with the currently-implemented emissions schedule, starting in around 2067. In other words, the currently-implemented emissions schedule continues to inflate at a higher rate than the one proposed in Schedule D, and therefore ultimately overcomes Schedule D in terms of total emissions.

If we choose to baseline with the 2050 supply, Schedule D would result in 2050 total circulating supply that is approximately 2.8% greater than the originally-projected 2050 supply. If you annualize that difference over the years between 2024 and 2050, you come out to an average annual increase in supply of about 0.1%. This strikes us as a relatively minimal adjustment (although, granted, one significantly seen in the earlier years).

== *Conclusion*

In the Emissions Report, we set forth what we believe to be a few compelling reasons for the Stacks community to consider an adjustment to its emissions schedule. Here we have outlined some key policy objectives that the Stacks community might have when considering such a change, and some example emissions schedules they might consider based on which of those objectives the Stacks community might choose to optimize for.

We ultimately believe that at this point in its relatively infancy, it’s in Stacks’ best interest to consider solutions that will allow it the most time and flexibility to thrive as it grows. An emissions schedule that decreases mining incentives too early, or too quickly, may artificially hinder Stacks’ growth and potential. As a result, we believe an emissions schedule along the lines of Schedule D would be most promising at this stage, with little cost in the form of modest added emissions, when viewed through the lens of 2050 supply.

Nevertheless, the schedules proposed here are but samples of the many options that the Stacks community could consider, and the policy objectives enumerated may miss some important ones held by the Stacks community. This analysis should be the starting point for an engaged discussion by the Stacks community, and we hope this paper as well as the model we created [[.mark]#NEED LINK#] can be useful tools in that discussion.
